import React, { useState, useRef, useEffect } from 'react';
import { 
  ResponsiveContainer, AreaChart, Area, XAxis, YAxis, 
  CartesianGrid, Tooltip, Legend 
} from 'recharts';
import { 
  ShieldCheck, Download, Users, FileText, TrendingUp, 
  RefreshCw, CheckCircle2, AlertTriangle, Play, MessageSquare, Send,
  Calendar, IndianRupee, Target, ArrowRight
} from 'lucide-react';

export default function FinalReport({ reportData, onStartNew }) {
  const [activeTab, setActiveTab] = useState('roadmap');
  const [chatMessages, setChatMessages] = useState([]);
  const [chatInput, setChatInput] = useState('');
  const chatEndRef = useRef(null);

  // Initialize welcome message
  useEffect(() => {
    if (reportData) {
      setChatMessages([{
        sender: "Advisor",
        text: `Alright, let's talk about "${reportData.subject}". I've gone through the numbers and the market. Ask me anything — how to make money, what could go wrong, what to do first, or anything else. No corporate fluff, just straight answers.`,
        time: new Date().toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
      }]);
    }
  }, [reportData]);

  // Auto-scroll chat
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  if (!reportData) return null;

  const {
    goal,
    subject = "digital product",
    businessModel = "Software Tool",
    industry = "Technology",
    location = "Online / Remote",
    audience = "regular people who need this",
    competitors = [],
    recommendations = [],
    assumptions = [],
    marketAnalysis = "",
    financials = [],
    trustScore = 85.0,
    metrics = {},
    swot = { strengths: [], weaknesses: [], opportunities: [], threats: [] },
    risks = [],
    revenueModel = {},
    roadmap = []
  } = reportData;

  const currency = metrics.currency || "₹";
  const totalBudget = metrics.totalBudget6mo || 135000;

  // Custom tooltip for chart
  const CustomTooltip = ({ active, payload, label }) => {
    if (active && payload && payload.length) {
      return (
        <div className="glassmorphism p-4 rounded-xl border border-white/10 text-left space-y-1">
          <p className="text-[10px] font-semibold text-brand-muted uppercase tracking-widest">{label}</p>
          {payload.map((item, idx) => (
            <p key={idx} className="text-xs font-semibold" style={{ color: item.color }}>
              {item.name}: ₹{item.value.toLocaleString('en-IN')}
            </p>
          ))}
        </div>
      );
    }
    return null;
  };

  // Download report
  const handleDownload = () => {
    let roadmapText = '';
    if (roadmap && roadmap.length > 0) {
      roadmapText = roadmap.map(m => `
MONTH ${m.month}
Priority: ${m.priority}
What to do:
${m.actions.map(a => `  - ${a}`).join('\n')}
Budget: ₹${m.budget.toLocaleString('en-IN')}
Reality Check: ${m.realityCheck}
`).join('\n');
    }

    const reportText = `
YOUR BUSINESS PLAN — HONEST VERSION
==================================================
GOAL: "${goal}"
INDUSTRY: ${industry}
BUSINESS MODEL: ${businessModel}
TARGET AUDIENCE: ${audience}

HOW YOU MAKE MONEY
--------------------------------------------------
Primary: ${revenueModel?.primary || 'N/A'}
Secondary: ${revenueModel?.secondary || 'N/A'}
Honest Truth: ${revenueModel?.honestTruth || 'N/A'}

6-MONTH ROADMAP
--------------------------------------------------
${roadmapText}

WHAT YOU'RE UP AGAINST (COMPETITORS)
--------------------------------------------------
${competitors.map((c, i) => `${i+1}. ${c}`).join('\n')}

HONEST ADVICE
--------------------------------------------------
${recommendations.map(r => `- ${r}`).join('\n')}

MARKET REALITY
--------------------------------------------------
${marketAnalysis}

ESTIMATED 6-MONTH BUDGET: ₹${totalBudget.toLocaleString('en-IN')}
==================================================
Generated by AetherCOO — Honest Business Advisor Engine
`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `business_plan_${Date.now()}.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Chat handler — answers like an actual advisor
  const handleSendChat = async (e) => {
    e.preventDefault();
    if (!chatInput.trim()) return;

    const userMessage = {
      sender: "You",
      text: chatInput,
      time: new Date().toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
    };
    
    // Optimistic UI update
    setChatMessages(prev => [...prev, userMessage]);
    const question = chatInput;
    setChatInput('');

    try {
      const backendUrl = import.meta.env.VITE_API_URL || "http://localhost:8000";
      const resp = await fetch(`${backendUrl}/api/runs/${reportData.id}/advisor`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: chatMessages.concat(userMessage),
          new_message: question
        })
      });
      
      if (!resp.ok) {
        throw new Error("Advisor service is currently offline.");
      }
      
      const { text } = await resp.json();
      
      setChatMessages(prev => [...prev, {
        sender: "Advisor",
        text,
        time: new Date().toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
      }]);
    } catch (err) {
      setChatMessages(prev => [...prev, {
        sender: "Advisor",
        text: `⚠️ Error: Could not retrieve a response from the Board Advisor API (${err.message}).`,
        time: new Date().toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
      }]);
    }
  };

  const tabs = [
    { id: 'roadmap', label: '6-Month Roadmap', icon: Calendar },
    { id: 'money', label: 'How You Earn', icon: IndianRupee },
    { id: 'market', label: 'Competition & Risks', icon: Target },
    { id: 'finance', label: 'Budget & Numbers', icon: TrendingUp },
    { id: 'boardroom', label: 'Ask the Advisor', icon: MessageSquare },
  ];

  return (
    <div className="max-w-6xl mx-auto w-full px-6 py-8 space-y-8 text-left">
      
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-6 border-b border-white/5">
        <div>
          <span className="text-[10px] font-semibold tracking-widest text-[#39FF14] uppercase block">
            Your Business Plan — Honest Version
          </span>
          <h2 className="font-display font-extrabold text-2xl md:text-3xl tracking-tight text-white mt-1">
            {subject}
          </h2>
          <p className="text-sm text-brand-muted mt-1 font-light">
            {businessModel} · {industry} · For {audience}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={onStartNew} className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-white/5 bg-white/[0.03] hover:bg-white/[0.08] text-xs font-semibold transition-all cursor-pointer text-white">
            <RefreshCw className="w-3.5 h-3.5" />
            New Idea
          </button>
          <button onClick={handleDownload} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white hover:bg-white/90 text-black text-xs font-semibold transition-all cursor-pointer shadow-lg">
            <Download className="w-3.5 h-3.5" />
            Download Plan
          </button>
        </div>
      </div>

      {/* Reality Check Banner */}
      <div className="relative p-5 rounded-2xl border border-amber-500/20 bg-amber-500/5 overflow-hidden">
        <div className="flex items-start gap-4 relative z-10">
          <div className="p-2.5 bg-amber-500/10 border border-amber-500/25 rounded-xl text-amber-500">
            <AlertTriangle className="w-5 h-5" />
          </div>
          <div className="space-y-2">
            <h3 className="font-display font-semibold text-base text-white">
              Before You Start — Read This
            </h3>
            <ul className="text-xs text-brand-muted space-y-1.5 font-light leading-relaxed">
              {assumptions.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-amber-500 mt-0.5 shrink-0">•</span>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-white/5 gap-1 overflow-x-auto">
        {tabs.map(tab => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-2 px-4 py-3 border-b-2 text-xs font-semibold transition-all shrink-0 cursor-pointer ${
              activeTab === tab.id ? 'border-[#39FF14] text-white' : 'border-transparent text-brand-muted hover:text-white'
            }`}
          >
            <tab.icon className="w-3.5 h-3.5" />
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="grid grid-cols-1 gap-6">

        {/* ===================== 6-MONTH ROADMAP ===================== */}
        {activeTab === 'roadmap' && (
          <div className="space-y-6">
            <div className="p-5 rounded-2xl border border-white/5 bg-brand-card/60">
              <h3 className="font-display font-bold text-lg text-white mb-1">Your 6-Month Plan</h3>
              <p className="text-xs text-brand-muted font-light">
                One priority per month. No fluff. If something isn't working, the reality check tells you what to do about it.
              </p>
            </div>

            <div className="space-y-4">
              {(roadmap || []).map((month, idx) => {
                const colors = ['#0052FF', '#39FF14', '#FF007A', '#0052FF', '#39FF14', '#FF007A'];
                const color = colors[idx % colors.length];
                return (
                  <div key={idx} className="p-6 rounded-2xl border border-white/5 bg-brand-card/40 space-y-4">
                    
                    {/* Month Header */}
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="h-10 w-10 rounded-xl flex items-center justify-center text-sm font-bold text-white" style={{ backgroundColor: `${color}20`, border: `1px solid ${color}40` }}>
                          {month.month}
                        </div>
                        <div>
                          <span className="text-[10px] font-semibold uppercase tracking-wider block" style={{ color }}>Month {month.month}</span>
                          <h4 className="font-semibold text-sm text-white">{month.priority}</h4>
                        </div>
                      </div>
                      <div className="text-right">
                        <span className="text-[10px] text-brand-muted uppercase tracking-wider block">Budget</span>
                        <span className="text-base font-bold text-white">₹{month.budget.toLocaleString('en-IN')}</span>
                      </div>
                    </div>

                    {/* Actions */}
                    <div className="space-y-2 pl-[52px]">
                      <span className="text-[10px] font-semibold uppercase tracking-wider text-brand-muted">What to actually do:</span>
                      {month.actions.map((action, aIdx) => (
                        <div key={aIdx} className="flex items-start gap-2.5 text-xs text-white/80 font-light leading-relaxed">
                          <ArrowRight className="w-3 h-3 shrink-0 mt-0.5" style={{ color }} />
                          {action}
                        </div>
                      ))}
                    </div>

                    {/* Reality Check */}
                    <div className="ml-[52px] p-4 rounded-xl border border-amber-500/15 bg-amber-500/5">
                      <div className="flex items-center gap-2 mb-1.5">
                        <AlertTriangle className="w-3 h-3 text-amber-500" />
                        <span className="text-[10px] font-bold uppercase tracking-wider text-amber-500">Reality Check</span>
                      </div>
                      <p className="text-xs text-brand-muted font-light leading-relaxed">
                        {month.realityCheck}
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Total Budget Summary */}
            <div className="p-5 rounded-2xl border border-[#39FF14]/20 bg-[#39FF14]/5 flex items-center justify-between">
              <div>
                <span className="text-[10px] font-semibold uppercase tracking-wider text-[#39FF14] block">Total 6-Month Budget</span>
                <span className="text-2xl font-bold text-white">₹{totalBudget.toLocaleString('en-IN')}</span>
              </div>
              <div className="text-right">
                <span className="text-[10px] font-semibold uppercase tracking-wider text-brand-muted block">Monthly Average</span>
                <span className="text-lg font-semibold text-white">₹{Math.round(totalBudget / 6).toLocaleString('en-IN')}</span>
              </div>
            </div>
          </div>
        )}

        {/* ===================== HOW YOU EARN MONEY ===================== */}
        {activeTab === 'money' && (
          <div className="space-y-6">
            <div className="p-6 rounded-2xl border border-[#39FF14]/15 bg-[#39FF14]/5 space-y-5">
              <h3 className="font-display font-bold text-xl text-white flex items-center gap-3">
                <IndianRupee className="w-5 h-5 text-[#39FF14]" />
                How You Actually Make Money
              </h3>
              
              <div className="space-y-5">
                <div className="p-5 rounded-xl border border-white/5 bg-brand-card/60 space-y-2">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-[#39FF14]">Primary Revenue</span>
                  <p className="text-sm text-white/90 leading-relaxed font-light">
                    {revenueModel?.primary || 'Charge for your product or service.'}
                  </p>
                </div>

                <div className="p-5 rounded-xl border border-white/5 bg-brand-card/60 space-y-2">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-[#0052FF]">Secondary Revenue (After Month 6)</span>
                  <p className="text-sm text-white/90 leading-relaxed font-light">
                    {revenueModel?.secondary || 'Add premium features or tiers later.'}
                  </p>
                </div>

                <div className="p-5 rounded-xl border border-amber-500/15 bg-amber-500/5 space-y-2">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-amber-500">
                    ⚠️ The Honest Truth
                  </span>
                  <p className="text-sm text-white/90 leading-relaxed font-light">
                    {revenueModel?.honestTruth || "Don't expect money in the first 3 months."}
                  </p>
                </div>
              </div>
            </div>

            {/* Practical Advice Cards */}
            <div className="space-y-3">
              <h4 className="font-display font-semibold text-base text-white">
                Straight-Up Advice
              </h4>
              {recommendations.map((rec, idx) => (
                <div key={idx} className="flex items-start gap-3 p-4 rounded-xl border border-white/5 bg-brand-card/40">
                  <CheckCircle2 className="w-4 h-4 text-[#39FF14] shrink-0 mt-0.5" />
                  <span className="text-sm text-white/85 font-light leading-relaxed">{rec}</span>
                </div>
              ))}
            </div>

            {/* SWOT — plain language */}
            <div className="space-y-4 pt-4">
              <h4 className="font-display font-semibold text-base text-white">What's Working For & Against You</h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="p-5 rounded-2xl border border-[#39FF14]/15 bg-[#39FF14]/5 space-y-3">
                  <h5 className="font-semibold text-sm text-[#39FF14] uppercase tracking-wider">✅ Your Advantages</h5>
                  <ul className="text-xs text-brand-muted space-y-2 font-light leading-relaxed">
                    {(swot?.strengths || []).map((s, i) => <li key={i} className="flex items-start gap-2"><span className="text-[#39FF14] mt-0.5 shrink-0">•</span>{s}</li>)}
                  </ul>
                </div>
                <div className="p-5 rounded-2xl border border-[#FF007A]/15 bg-[#FF007A]/5 space-y-3">
                  <h5 className="font-semibold text-sm text-[#FF007A] uppercase tracking-wider">❌ Your Weak Spots</h5>
                  <ul className="text-xs text-brand-muted space-y-2 font-light leading-relaxed">
                    {(swot?.weaknesses || []).map((w, i) => <li key={i} className="flex items-start gap-2"><span className="text-[#FF007A] mt-0.5 shrink-0">•</span>{w}</li>)}
                  </ul>
                </div>
                <div className="p-5 rounded-2xl border border-[#0052FF]/15 bg-[#0052FF]/5 space-y-3">
                  <h5 className="font-semibold text-sm text-[#0052FF] uppercase tracking-wider">🔵 Opportunities</h5>
                  <ul className="text-xs text-brand-muted space-y-2 font-light leading-relaxed">
                    {(swot?.opportunities || []).map((o, i) => <li key={i} className="flex items-start gap-2"><span className="text-[#0052FF] mt-0.5 shrink-0">•</span>{o}</li>)}
                  </ul>
                </div>
                <div className="p-5 rounded-2xl border border-amber-500/15 bg-amber-500/5 space-y-3">
                  <h5 className="font-semibold text-sm text-amber-500 uppercase tracking-wider">⚠️ Watch Out For</h5>
                  <ul className="text-xs text-brand-muted space-y-2 font-light leading-relaxed">
                    {(swot?.threats || []).map((t, i) => <li key={i} className="flex items-start gap-2"><span className="text-amber-500 mt-0.5 shrink-0">•</span>{t}</li>)}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ===================== COMPETITION & RISKS ===================== */}
        {activeTab === 'market' && (
          <div className="space-y-6">
            {/* Market Reality */}
            <div className="p-6 rounded-2xl border border-white/5 bg-brand-card/60 space-y-3">
              <h3 className="font-display font-bold text-lg text-white">The Market Reality</h3>
              <p className="text-sm text-brand-muted leading-relaxed font-light">{marketAnalysis}</p>
            </div>

            {/* Competitors */}
            <div className="p-6 rounded-2xl border border-white/5 bg-brand-card/40 space-y-4">
              <h4 className="font-display font-semibold text-base text-white">
                Who You're Up Against
              </h4>
              <div className="space-y-3">
                {competitors.map((name, idx) => (
                  <div key={idx} className="flex items-center justify-between p-4 rounded-xl border border-white/[0.05] bg-white/[0.02]">
                    <div className="flex items-center gap-3">
                      <span className="h-7 w-7 rounded-lg bg-[#FF007A]/10 border border-[#FF007A]/20 flex items-center justify-center text-[10px] font-bold text-[#FF007A]">
                        {idx + 1}
                      </span>
                      <span className="text-sm text-white/90 font-light">{name}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Risk Table */}
            <div className="border border-white/10 rounded-2xl bg-[#0F0F11]/90 shadow-2xl overflow-hidden">
              <div className="px-5 py-4 border-b border-white/5 bg-[#141417]">
                <span className="text-xs uppercase tracking-widest text-brand-muted font-semibold">
                  What Could Go Wrong (And What To Do About It)
                </span>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse text-xs">
                  <thead>
                    <tr className="border-b border-white/15 bg-white/[0.01]">
                      <th className="p-4 font-semibold text-brand-muted">Risk</th>
                      <th className="p-4 font-semibold text-brand-muted">What happens</th>
                      <th className="p-4 font-semibold text-brand-muted text-center">How bad</th>
                      <th className="p-4 font-semibold text-brand-muted">What to do</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(risks || []).map((row, idx) => (
                      <tr key={idx} className="border-b border-white/5 hover:bg-white/[0.02] transition-colors">
                        <td className="p-4 font-semibold text-white">{row.category}</td>
                        <td className="p-4 text-brand-muted font-light leading-relaxed">{row.risk}</td>
                        <td className="p-4 text-center">
                          <span className={`px-2.5 py-1 rounded text-[10px] font-bold ${
                            row.severity === 'High' 
                              ? 'bg-[#FF007A]/10 border border-[#FF007A]/25 text-[#FF007A]' 
                              : 'bg-amber-500/10 border border-amber-500/25 text-amber-500'
                          }`}>
                            {row.severity}
                          </span>
                        </td>
                        <td className="p-4 text-white/90 font-light leading-relaxed">{row.mitigation}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}

        {/* ===================== BUDGET & NUMBERS ===================== */}
        {activeTab === 'finance' && (
          <div className="space-y-6">
            <div className="p-6 rounded-2xl border border-white/5 bg-brand-card/60 space-y-3">
              <h3 className="font-display font-bold text-lg text-white">Budget Forecast (Conservative)</h3>
              <p className="text-xs text-brand-muted leading-relaxed font-light">
                These are conservative estimates. Month 1-6 will likely be negative (you're spending to build and test). 
                Profit should start showing around Month 8-10 if things go well. If you're not breaking even by Month 12, reassess.
              </p>

              {/* Chart */}
              <div className="w-full h-72 pt-4">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={financials} margin={{ top: 10, right: 10, left: 10, bottom: 0 }}>
                    <defs>
                      <linearGradient id="colorRev" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#0052FF" stopOpacity={0.4}/>
                        <stop offset="95%" stopColor="#0052FF" stopOpacity={0}/>
                      </linearGradient>
                      <linearGradient id="colorProfit" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#39FF14" stopOpacity={0.4}/>
                        <stop offset="95%" stopColor="#39FF14" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255, 255, 255, 0.05)" />
                    <XAxis dataKey="year" stroke="#8A8A8E" fontSize={10} tickLine={false} />
                    <YAxis stroke="#8A8A8E" fontSize={10} tickLine={false} axisLine={false} tickFormatter={(val) => `₹${(val/1000).toLocaleString('en-IN')}k`} />
                    <Tooltip content={<CustomTooltip />} />
                    <Legend wrapperStyle={{ fontSize: 10, color: '#8A8A8E', paddingTop: 10 }} />
                    <Area type="monotone" name="Revenue" dataKey="revenue" stroke="#0052FF" strokeWidth={2} fillOpacity={1} fill="url(#colorRev)" />
                    <Area type="monotone" name="Net Profit" dataKey="profit" stroke="#39FF14" strokeWidth={2} fillOpacity={1} fill="url(#colorProfit)" />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Key Metrics */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="p-4 rounded-xl border border-white/5 bg-brand-card/40 space-y-1">
                <span className="text-[10px] text-brand-muted uppercase tracking-wider block">Total 6-Month Budget</span>
                <span className="text-lg font-semibold text-white">₹{totalBudget.toLocaleString('en-IN')}</span>
              </div>
              <div className="p-4 rounded-xl border border-white/5 bg-brand-card/40 space-y-1">
                <span className="text-[10px] text-brand-muted uppercase tracking-wider block">Est. Break-Even</span>
                <span className="text-lg font-semibold text-[#39FF14]">{metrics.breakeven}</span>
              </div>
              <div className="p-4 rounded-xl border border-white/5 bg-brand-card/40 space-y-1">
                <span className="text-[10px] text-brand-muted uppercase tracking-wider block">Cost per Customer</span>
                <span className="text-lg font-semibold text-white">₹{(metrics.cac || 0).toLocaleString('en-IN')}</span>
              </div>
              <div className="p-4 rounded-xl border border-white/5 bg-brand-card/40 space-y-1">
                <span className="text-[10px] text-brand-muted uppercase tracking-wider block">Customer Lifetime Value</span>
                <span className="text-lg font-semibold text-[#0052FF]">₹{(metrics.ltv || 0).toLocaleString('en-IN')}</span>
              </div>
            </div>

            {/* P&L Table */}
            <div className="border border-white/10 rounded-2xl bg-[#0F0F11]/90 shadow-2xl overflow-hidden">
              <div className="px-5 py-4 border-b border-white/5 bg-[#141417]">
                <span className="text-xs uppercase tracking-widest text-brand-muted font-semibold">
                  Projected Profit & Loss
                </span>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse text-xs">
                  <thead>
                    <tr className="border-b border-white/15 bg-white/[0.01]">
                      <th className="p-4 font-semibold text-brand-muted">Period</th>
                      <th className="p-4 font-semibold text-brand-muted text-right">Revenue</th>
                      <th className="p-4 font-semibold text-brand-muted text-right">Expenses</th>
                      <th className="p-4 font-semibold text-brand-muted text-right">Net</th>
                    </tr>
                  </thead>
                  <tbody>
                    {financials.map((row, idx) => {
                      const isLoss = row.profit < 0;
                      return (
                        <tr key={idx} className="border-b border-white/5 hover:bg-white/[0.02] transition-colors">
                          <td className="p-4 font-medium text-white">{row.year}</td>
                          <td className="p-4 text-white text-right font-mono">₹{row.revenue.toLocaleString('en-IN')}</td>
                          <td className="p-4 text-white text-right font-mono">₹{row.expenses.toLocaleString('en-IN')}</td>
                          <td className={`p-4 text-right font-mono font-semibold ${isLoss ? 'text-[#FF007A]' : 'text-[#39FF14]'}`}>
                            {isLoss ? '-' : ''}₹{Math.abs(row.profit).toLocaleString('en-IN')}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}

        {/* ===================== ASK THE ADVISOR ===================== */}
        {activeTab === 'boardroom' && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch min-h-[520px]">
            {/* Left: Quick Topics */}
            <div className="lg:col-span-4 p-5 rounded-2xl border border-white/5 bg-[#0F0F11]/60 flex flex-col justify-between">
              <div className="space-y-5">
                <div className="border-b border-white/5 pb-3">
                  <h4 className="font-display font-semibold text-base text-white">Ask Me Anything</h4>
                  <p className="text-[11px] text-brand-muted mt-1">I'll answer like a real advisor — no corporate speak, just honest advice about your business.</p>
                </div>

                <div className="space-y-2">
                  <span className="text-[9px] uppercase font-bold tracking-wider text-brand-muted block">Quick Questions</span>
                  <div className="flex flex-col gap-1.5">
                    {[
                      { label: "How do I make money with this?", q: "How do I make money with this idea?" },
                      { label: "What should I do first?", q: "What should I do first? Where do I start?" },
                      { label: "How much should I spend?", q: "How much budget do I need and how should I spend it?" },
                      { label: "Who's my competition?", q: "Who are my competitors and how do I beat them?" },
                      { label: "What could go wrong?", q: "What are the biggest risks and what could go wrong?" },
                      { label: "Should I quit my job?", q: "Should I quit my job to work on this full time?" },
                      { label: "How do I get customers?", q: "How do I get my first customers?" },
                      { label: "Do I need to register?", q: "Do I need any legal registration or licenses?" },
                      { label: "Should I hire someone?", q: "Should I hire a developer or find a co-founder?" },
                      { label: "Is this idea even good?", q: "How do I know if my idea is worth pursuing?" },
                    ].map((item, idx) => (
                      <button key={idx}
                        onClick={() => setChatInput(item.q)}
                        className="text-left text-[11px] text-brand-muted hover:text-white px-3 py-2 rounded-lg border border-white/5 hover:border-white/15 bg-white/[0.01] hover:bg-white/[0.04] transition-colors cursor-pointer"
                      >
                        {item.label}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Right: Chat */}
            <div className="lg:col-span-8 p-5 rounded-2xl border border-white/10 bg-[#0C0C0E]/90 flex flex-col justify-between h-[520px]">
              <div className="flex-1 overflow-y-auto space-y-4 pr-1 mb-4">
                {chatMessages.map((msg, index) => {
                  const isYou = msg.sender === 'You';
                  return (
                    <div key={index} className={`flex items-start gap-3 ${isYou ? 'flex-row-reverse' : ''}`}>
                      {!isYou && (
                        <div className="h-8 w-8 rounded-full bg-[#39FF14] flex items-center justify-center text-[10px] font-bold text-black shrink-0">
                          AD
                        </div>
                      )}
                      <div className={`max-w-[85%] rounded-2xl p-4 border text-xs leading-relaxed ${
                        isYou 
                          ? 'bg-[#0052FF]/15 border-[#0052FF]/25 text-white' 
                          : 'bg-brand-card border-white/5 text-[#D1D1D6]'
                      }`}>
                        <div className="flex items-center justify-between gap-6 mb-1.5 text-[10px] text-brand-muted">
                          <span className="font-semibold text-white/50">{isYou ? 'You' : '🧑‍💼 Board Advisor'}</span>
                          <span>{msg.time}</span>
                        </div>
                        <p className="whitespace-pre-wrap">{msg.text}</p>
                      </div>
                    </div>
                  );
                })}
                <div ref={chatEndRef} />
              </div>

              <form onSubmit={handleSendChat} className="flex gap-2">
                <input 
                  type="text" 
                  value={chatInput} 
                  onChange={(e) => setChatInput(e.target.value)} 
                  placeholder="Ask anything — money, marketing, hiring, legal, whatever..." 
                  className="flex-1 px-4 py-3 text-xs bg-[#161618] border border-white/5 hover:border-[#39FF14]/20 focus:border-[#39FF14]/60 rounded-xl text-white outline-none"
                />
                <button type="submit" className="px-4 py-3 rounded-xl bg-white hover:bg-white/90 text-black flex items-center justify-center transition-transform hover:scale-[1.02] cursor-pointer">
                  <Send className="w-3.5 h-3.5" />
                </button>
              </form>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
